name: "Creating or updating registry"

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: execute script
        run: python main.py
  
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions
        uses: actions/github-script@v6
      - name: teste
        run: |
          git add .
          git commit -m "Adding or updating registry"
          git push