name: Issue Forms Body Parser

on:
  issues:
    types: [opened]
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the issue
        id: read_issue_body
        run:
          echo "body=$(gh issue view ${{ github.event.issue_number }} --repo ${{
          github.repo }} --json body --jq '.body')" >> $GITHUB_OUTPUT

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
        with:
          body: ${{ steps.read_issue_body.output.body }}

      - name: print values
        id: print
        env:
          VALOR_JSON: ${{ toJSON(steps.parse.outputs.data) }}
        run: echo "${{ fromJSON(${VALOR_JSON}).nome }}"

# name: "Creating or updating registry"

# on:
#   issues:
#     types: [opened]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout repo content
#         uses: actions/checkout@v3
#       - name: get issue info
#         id: parse
#         uses: zentered/issue-forms-body-parser@v2.0.0
#       - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"


      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.8
      # - name: execute script
      #   run: |
      #     echo "Issue title: ${{ github.event.issue.title }}"
      #     echo "${{ JSON.stringify(github.event.issue.body ) }}"
      #     python main.py
      #     git --version
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"
      #     git add .
      #     git commit -m "changes"
      #     git push